name: Update GitHub Contributions

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-contributions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo content
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Install packages
        run: pip install -r contributions/requirements.txt

      - name: Run Python script
        env:
          USER: ${{ github.repository_owner }}
        run: python contributions/main.py

      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -am "Automated update of GitHub contributions list"
          git push