name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/github-metrics.*
          clean_workflows: success
          repositories_skipped: rivenintech
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          base_hireable: yes
          plugin_lines: yes
          plugin_lines_history_limit: 0
          plugin_lines_delay: 30
          commits_authoring: 61630074+rivenintech@users.noreply.github.com, 61630074+RiveN000@users.noreply.github.com
          plugin_gists: yes
          plugin_followup: yes
          plugin_followup_sections: user
          plugin_followup_indepth: yes
          plugin_notable: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
